@extends('frontend.layout.app')
@section('title', 'Terms & Conditions')
@section('content')
@push('styles')
<link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
<link href="{{ asset('assets/css/tagsinput.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('assets/css/bootstrap-datepicker.css') }}" rel="stylesheet" type="text/css">
<style type="text/css">
.sal{
    line-height: 50px;
}
</style>
@endpush
            <!-- Title Header Start -->
            <section class="inner-header-title" style="background-image:url({{ asset('assets/img/banner-10.jpg')}} )">
                <div class="container">
                    <h1>Terms & Conditions</h1>
                </div>
            </section>
            <div class="clearfix"></div>
            <!-- Title Header End -->

            <!-- Job full detail Start -->
            <section class="full-detail-description full-detail gray-bg">
                <div class="container">
                    <br>
                    <div class="row row-bottom">
                      <div class="col-md-12">
                            <div class="col-md-12 col-sm-12">
                                <div class="full-card">
                                  <div class="deatil-tab-employ tool-tab">
                                        <div class="tab-content">
                                            <h2 class="detail-title">PURPOSE</h2>
                                            <p>OutplacementHeros.com is intended only to serve as a preliminary medium of contact and exchange of information for its users / members / visitors who have a bona fide intention to contact and/or be contacted for the purposes related to genuine existing job vacancies and for other career enhancement services.</p>
                                            <h2 class="detail-title">USE TO BE IN CONFORMITY WITH THE PURPOSE</h2>
                                            <p>OutplacementHeros.Org (and related products) or service or product that is subscribe to or used (whether the same is paid for by you or not) is meant for the Purpose  and only the exclusive use of the subscriber/registered user. Copying or downloading or recreating or sharing passwords or sublicensing or sharing in any manner which is not in accordance with these terms, is a misuse of the platform or service or product and OUTPLACEMENTHEROS.ORG reserves its rights to act in such manner as to protect its loss of revenue or reputation or claim damages including stopping your service or access and reporting to relevant authorities. In the event you are found to be copying or misusing or transmitting or crawling any data or photographs or graphics or any information available on OutplacementHeros.Org for any purpose other than that being a bonafide Purpose, we reserve the right to take such action that we deem fit including stopping access and claiming damages</p>   
                                            <p>The site is a public site with free access and OutplacementHeros.Org assumes no liability for the quality and genuineness of responses.OutplacementHeros.Org. cannot monitor the responses that a person may receive in response to information he/she has displayed on the site. The individual/company would have to conduct its own background checks on the bonafide nature of all response(s).</p>                       
                                            <p>You give us permission to use the information about actions that you have taken on OutplacementHeros.Org in connection with ads, offers and other content (whether sponsored or not) that we display across our services, without any compensation to you. We use data and information about you to make relevant suggestions and recommendation to you and others.</p>                       
                                            <p>The platform may contain links to third party websites, these links are provided solely as convenience to You and the presence of these links should not under any circumstances be considered as an endorsement of the contents of the same, if You chose to access these websites you do so at your own risk.</p>                       
                                            <p>Whilst using this platform an obligation is cast upon you to only provide true and correct information and in the case of creating a profile you undertake to at all times keep the information up to date.OutplacementHeros.Org. will not be liable on account of any inaccuracy of information on this web site. It is the responsibility of the visitor to further research the information on the site. Any breach of privacy or of the information provided by the consumer toOutplacementHeros.Org. to be placed on the website by technical or any other means is not the responsibility ofOutplacementHeros.Org.OutplacementHeros.Org. does not guarantee confidentiality of information provided to it by any person acquiring/using all/any information displayed on the OutplacementHeros.Org website or any of its other websites / domains owned and operated byOutplacementHeros.Org.</p>  

                                            <p>OutplacementHeros.Org does not share personally identifiable data of any individual with other companies / entities without obtaining permission except with those acting as our agents..OutplacementHeros.Org. shall share all such information that it has in its possession in response to legal process, such as a court order or subpoena. The user shall not utilize the services offered by OutplacementHeros.Org in any manner so as to impair the interests and functioning of OutplacementHeros.Org. The user undertakes not to duplicate, download publish, modify and distribute material on OutplacementHeros.Org unless specifically authorized by OUTPLACEMENTHEROS.ORG in this regard.</p>                       
                                            <p>The user undertakes to use OutplacementHeros.Org for his/her own purposes. Using content from OutplacementHeros.Org for derivative works with a commercial motive without prior written consent from OUTPLACEMENTHEROS.ORG is strictly prohibited.</p>                       
                                            <p>Users undertake that the services offered by OutplacementHeros.Org/ OUTPLACEMENTHEROS.ORG shall not be utilized to upload, post, email, transmit or otherwise make available either directly or indirectly, any unsolicited bulk e-mail or unsolicited commercial e-mail. OUTPLACEMENTHEROS.ORG reserves the right to filter and monitor and block the emails sent by you/user using the servers maintained by OUTPLACEMENTHEROS.ORG to relay emails. All attempts shall be made by OUTPLACEMENTHEROS.ORG and the user to abide by International Best Practices in containing and eliminating Spam.</p>                       
                                            <p>Users shall not spam the platform maintained by OutplacementHeros.Org / OUTPLACEMENTHEROS.ORG or indiscriminately and repeatedly post jobs/forward mail indiscriminately etc. Any conduct of the user in violation of this clause shall entitle OUTPLACEMENTHEROS.ORG to forthwith terminate all services to the user without notice and to forfeit any amounts paid by him.</p>                       
                                            <p>The user shall not upload, post, transmit, publish, or distribute any material or information that is unlawful, or which may potentially be perceived as being harmful, threatening, abusive, harassing, defamatory, libellous, vulgar, obscene, or racially, ethnically, or otherwise objectionable.</p>                       
                                            <p>The user expressly states that the resume/insertion or information/ data being fed into the network ofOutplacementHeros.Org. by the user is correct and complete in all respects and does not contain any false, distorted, manipulated, fraudulent or misleading facts or averments.OutplacementHeros.Org. Expressly disclaims any liability arising out of the said resume insertion/information/ data so fed into the network ofOutplacementHeros.Org. by the user. Further, the user agrees to indemnifyOutplacementHeros.Org. for all losses incurred byOutplacementHeros.Org. due to any false, distorted, manipulated, defamatory, libellous, vulgar, obscene, fraudulent or misleading facts or otherwise objectionable averments made by the user on the network of OutplacementHeros.Org.</p>                       
                                            <p>The User is solely responsible for maintaining confidentiality of the User password and user identification and all activities and transmission performed by the User through his user identification and shall be solely responsible for carrying out any online or off-line transaction involving credit cards / debit cards or such other forms of instruments or documents for making such transactions andOutplacementHeros.Org. assumes no responsibility or liability for their improper use of information relating to such usage of credit cards / debit cards used by the subscriber online / off-line.</p>                       
                                            <p>The User/Subscriber/Visitor to OutplacementHeros.Org and/or its affiliated websites does hereby specifically agree that he/she shall, at all times, comply with the requirements of the Information Technology Act, 2000 as also rules, regulations, guidelines, bye laws and notifications made thereunder, while assessing or feeding any resume/ insertion or information/data into the computers, computer systems or computer network of OutplacementHeros.Org. The said User/ subscriber/ visitor to OutplacementHeros.Org and/or its affiliated websites does further unequivocally declare that in case he violates any provisions of the Information Technology Act, 2000 and/or rules, regulations, guidelines, byelaws and notifications made thereunder, he shall alone be responsible for all his acts, deeds and things and that he alone shall be liable for civil and criminal liability there under or under any other law for the time being in force.</p>                       
                                            <p>The User/Subscriber/Visitor to OutplacementHeros.Org and/or its affiliated websites does hereby specifically agree that he/she shall, at all times, comply with the requirements of the Information Technology Act, 2000 as also rules, regulations, guidelines, bye laws and notifications made thereunder, while assessing or feeding any resume/ insertion or information/data into the computers, computer systems or computer network of OutplacementHeros.Org. The said User/ subscriber/ visitor to OutplacementHeros.Org and/or its affiliated websites does further unequivocally declare that in case he violates any provisions of the Information Technology Act, 2000 and/or rules, regulations, guidelines, byelaws and notifications made thereunder, he shall alone be responsible for all his acts, deeds and things and that he alone shall be liable for civil and criminal liability there under or under any other law for the time being in force.</p>                       
                                            <p>THE USER REPRESENTS, WARRANTS AND COVENANTS THAT ITS USE OF OUTPLACEMENTHEROS.ORG SHALL NOT BE DONE IN A MANNER SO AS TO:</p>  
                                            <ul>
                                              <li>Violate any applicable local, provincial, state, national or international law, statute, ordinance, rule or regulation;</li>
                                              <li>Interfere with or disrupt computer networks connected to OutplacementHeros.Org;</li>
                                              <li>Impersonate any other person or entity, or make any misrepresentation as to your employment by or affiliation with any other person or entity;</li>
                                              <li>Forge headers or in any manner manipulate identifiers in order to disguise the origin of any user information;</li>
                                              <li>Interfere with or disrupt the use of OutplacementHeros.Org by any other user, nor "stalk", threaten, or in any manner harass another user;</li>
                                              <li>Use OutplacementHeros.Org in such a manner as to gain unauthorized entry or access to the computer systems of others;</li>
                                              <li>Reproduce, copy, modify, sell, store, distribute or otherwise exploit for any commercial purposes OutplacementHeros.Org, or any component thereof (including, but not limited to any materials or information accessible through OutplacementHeros.Org);</li>
                                              <li>Use content from the Site for derivative works with a commercial motive without prior written consent of the OUTPLACEMENTHEROS.ORG.</li>
                                              <li>Use any device, software or routine to interfere or attempt to interfere with the proper working of OutplacementHeros.Org; or</li>
                                              <li>Impose an unreasonable or disproportionately large load on OutplacementHeros.Org infrastructure.</li>
                                              <li>Spam OutplacementHeros.Org/OUTPLACEMENTHEROS.ORG by indiscriminately and repeatedly posting content or forwarding mail that may be considered spam etc.</li>
                                              <li>Access data not intended for you or log into server or account that you are not authorized to access;</li>
                                              <li>Constitute an act of reverse engineering, decompiling, disassembling, deciphering or otherwise attempting to derive the source code for the Site or any related technology or any part thereof</li>
                                              <li>Engage in "framing," "mirroring," or otherwise simulating the appearance or function of the Site</li>
                                              <li>Attempt to probe, scan or test the vulnerability of a system or network;</li>
                                              <li>Use automated means to crawl and/or scrape content from OutplacementHeros.Org and to manually scrape content from OutplacementHeros.Org;</li>
                                              <li>The Site uses technological means to exclude Robots etc. from crawling it and scraping content. You undertake not to circumvent these methods.</li>
                                              <li>Access the Site except through the interfaces expressly provided by OUTPLACEMENTHEROS.ORG;</li>
                                              <li>Attempt or breach security or authentication measures without proper authorization;</li>
                                              <li>Providing deeplinks into OutplacementHeros.Org without prior permission of OUTPLACEMENTHEROS.ORG is prohibited. Extracting data from OutplacementHeros.Org using any automated process such as spiders, crawlers etc. or through any manual process for a purpose which has not been authorised in writing.</li>
                                              <li> Upload, post, email, transmit or otherwise make available either directly or indirectly, any unsolicited bulk e-mail or unsolicited commercial e-mail.</li>
                                              <li> Subscribers shall under no circumstance sublicense, assign, or transfer the License, and any attempt at such sublicense, assignment or transfer is void.</li>
                                              <li> Constitute hosting, modifying, uploading, posting, transmitting, publishing, or distributing any material or information</li>
                                              <li>For which you do not have all necessary rights and licenses;</li>
                                              <li>Which infringes, violates, breaches or otherwise contravenes the rights of any third party, including any copyright, trademark, patent, rights of privacy or publicity or any other proprietary right;</li>
                                              <li> Which contains a computer virus, or other code, files or programs intending in any manner to disrupt or interfere with the functioning of OutplacementHeros.Org, or that of other computer systems;</li>
                                              <li> That is grossly harmful, harassing, invasive of another's privacy, hateful, disparaging, relating to money laundering or unlawful, or which may potentially be perceived as being harmful, threatening, abusive, harassing, defamatory, libelous/blasphemous, vulgar, obscene, or racially, ethnically, or otherwise unlawful in any manner whatsoever;</li>
                                              <li> Which constitutes or encourages conduct that would constitute a criminal offence, give rise to other liability, or otherwise violate applicable law;</li>
                                              <li>That deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</li>
                                              <li>That belongs to another person and to which the user does not have any right to;</li>
                                              <li>That harm minors in any way;</li>
                                              <li>That threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation.</li>
                                            </ul>                     
                                            <p>The user shall not infringe on any intellectual property rights of any person / entity or retain information / download any information from any computer system or otherwise with an intention to do so.</p>                       
                                            <p>OutplacementHeros.Org. will make best efforts to do so but does not warrant that any of the web sites or any affiliate site(s) or network system linked to it is free of any operational errors nor does it warrant that it will be free of any virus, computer contaminant, worm, or other harmful components. The subscription of a user shall be subject to Quotas as applicable and as advised. E-Mails provided as part of contact details are expected to be genuine and access to such email accounts is available to authorised personnel only.</p>                       
                                            <p>OutplacementHeros.Org. will make best efforts to do so but does not warrant that any of the web sites or any affiliate site(s) or network system linked to it is free of any operational errors nor does it warrant that it will be free of any virus, computer contaminant, worm, or other harmful components. The subscription of a user shall be subject to Quotas as applicable and as advised. E-Mails provided as part of contact details are expected to be genuine and access to such email accounts is available to authorised personnel only.</p>                       
                                            <p>Payments for the services offered by OutplacementHeros.Org shall be on a 100% advance basis. Refund if any will be at the sole discretion of OutplacementHeros.Org. OUTPLACEMENTHEROS.ORG offers no guarantees whatsoever for the accuracy or timeliness of the refunds reaching the Customers card/bank accounts. OUTPLACEMENTHEROS.ORG gives no guarantees of server uptime or applications working properly. All is on a best effort basis and liability is limited to refund of amount only. OUTPLACEMENTHEROS.ORG undertakes no liability for free services. OUTPLACEMENTHEROS.ORG reserves its right to amend / alter or change all or any disclaimers or terms of agreements at any time without any prior notice. All terms / disclaimers whether specifically mentioned or not shall be deemed to be included if any reference is made to them.</p>                       
                                            <p>Unless otherwise specified and notwithstanding anything contained in any other agreement or arrangement, by whatever name called, the performance obligation of OUTPLACEMENTHEROS.ORG (service provider) is to provide access of its on-line portal to the customer for the duration of the subscription period & reference to any usage, by whatever name called or any other performance obligation, if any, is to provide the upper limit for consumption, which by itself, does not create any additional performance obligation upon OUTPLACEMENTHEROS.ORG</p>                       
                                            <p>Subscriber/user acknowledges and agrees that OUTPLACEMENTHEROS.ORG/OutplacementHeros.Org, at its sole discretion and without prejudice to other rights and remedies that it may have under the applicable laws, shall be entitled to set off the amount paid or payable by a subscriber/user against any amount(s) payable by Subscriber/user to OUTPLACEMENTHEROS.ORG under any other agreement or commercial relationship towards other products/services.</p>                       
                                            <p>OutplacementHeros.Org. further reserves its right to post the data on the website OutplacementHeros.Org or on such other affiliated sites and publications asOutplacementHeros.Org. may deem fit and proper at no extra cost to the subscriber / user.</p>                       
                                            <p>The subscription / agreement between OUTPLACEMENTHEROS.ORG and the subscriber / user is not a "non-poach agreement" nor can the same be termed or used as an alternative to "non-poach agreement" in as much as OUTPLACEMENTHEROS.ORG / OutplacementHeros.Org is a public site and all information posted by OUTPLACEMENTHEROS.ORG goes to the public domain except information / data which is specifically assigned a non-public / private character.</p>                       
                                            <p>Any agreement for a subscription / usage entered into by OUTPLACEMENTHEROS.ORG does not confer exclusivity of service on any subscriber / user.</p>                       
                                            <p>OutplacementHeros.Org will not be party to any legal proceedings between a user (e.g. a subscriber) and a party contracted through the site. In caseOutplacementHeros.Org.is implicated in any legal proceedings, costs will be recovered from the party that namesOutplacementHeros.Org. OutplacementHeros.Org however will abide with any court order served on it through due process. OUTPLACEMENTHEROS.ORG controls and operates this Platform from its headquarters in Noida and makes no representation that the materials on OutplacementHeros.Org are appropriate or available for use in other locations. If you use this Website from other locations, you are responsible for compliance with applicable local laws including but not limited to the export and import regulations of other countries.</p>                       
                                            <p>In case a person using the world wide web/internet receives a spam or virus which includes a link to OutplacementHeros.Org or to any other site maintained, operated or owned by OUTPLACEMENTHEROS.ORG, it should not be held responsible for the same. OUTPLACEMENTHEROS.ORG assumes no responsibility for such mails.</p>                       
                                            <p>The services provided by the websites maintained, operated or owned by OUTPLACEMENTHEROS.ORG do not extend to acting as an agent (express or implied) on behalf of any subscriber or user.</p>                       
                                            <p>OUTPLACEMENTHEROS.ORG has no agents and does not operate through any agents save for those specifically mentioned on the home page of the website.</p>                       
                                            <p>The Terms and conditions mentioned above regulate the usage of OutplacementHeros.Org. Any person using OutplacementHeros.Org in violation of the stipulations contained in the Terms and Conditions of OutplacementHeros.Org shall render himself/herself liable to appropriate action in a court of law both civil and criminal.</p>                       
                                            <p><i>BY ACCEPTING THESE TERMS AND CONDITIONS, YOU AGREE TO INDEMNIFY AND OTHERWISE HOLD HARMLESS OUTPLACEMENTHEROS.ORG, ITS DIRECTORS, OFFICERS, EMPLOYERS, AGENTS, SUBSIDIARIES, AFFILIATES AND OTHER PARTNERS FROM ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES ARISING OUT OF, RELATING TO, OR RESULTING FROM YOUR USE OF THE SERVICES OBTAINED THROUGH OUTPLACEMENTHEROS.ORG INCLUDING BUT NOT LIMITED TO INFORMATION PROVIDED BY YOU OR ANY OTHER MATTER RELATING TO OUTPLACEMENTHEROS.ORG. ANY REFERENCE TO DUTIES AND TAXES ETC IN THESE TERMS OF USE SHALL INCLUDE GOODS AND SERVICES TAX (HEREIN REFERRED AS GST) FROM THE DATE GST LAW IS IMPLEMENTED IN INDIA. ANY ADDITIONAL TAX LIABILITY ARISING ON ACCOUNT OF INTRODUCTION OF GST (WHETHER ON ACCOUNT OF INCREASE IN RATE OR ANY CHANGE BROUGHT IN BY THE NEW TAX REGIME) WOULD BE RECOVERED OVER AND ABOVE THE AGREED CONTRACT PRICE / SERVICE FEE.</i></p>                       
                                            <p>If any dispute arises between a user/users and OUTPLACEMENTHEROS.ORG arising out of use of OutplacementHeros.Org or thereafter, in connection with the validity, interpretation, implementation or alleged breach of any provision of these Terms and Conditions, the dispute shall be referred to a sole arbitrator who shall be an independent and neutral third party identified by the Company. Decision of the arbitrator shall be final and binding on both the parties to the dispute. The place of arbitration shall be Gurgaon, Haryana, India. The Arbitration & Conciliation Act, 1996 as amended, shall govern the arbitration proceedings.</p>                       
                                            <p>These Terms and Conditions shall be governed by the laws of Republic of India. The exclusive forum for any disputes arising out of or relating to these Terms of Use shall be a court of law located in New Delhi, India.</p>                       
                                            <p>OutplacementHeros.Org, OutplacementHeros.Org India, OUTPLACEMENTHEROS.ORG andOutplacementHeros.Org.are used interchangeably and are synonymous.</p>                       
                                            <p>To seek more information and to report Spam. Please mail us at: support@OutplacementHeros.Org</p>                       
                                            <p><strong>Note:</strong> The terms in this agreement may be changed by OutplacementHeros.Org at any time. OutplacementHeros.Org is free to offer its services to any client/prospective client without restriction.</p>                       
                                        </div>
                                    </div>  
                                </div>
                            </div>
                        </div>
                      
                    </div>
                </div>
            </section>
            <!-- Job full detail End -->
@endsection
@push('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js"></script>
<script src="{{ asset('assets/plugins/js/tagsinput.js') }}"></script>
<script src="{{ asset('assets/js/bootstrap-datepicker.js') }}"></script>
@endpush